[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=68" ]

[project]
name = "pntos-cobra"
version = "2.1.0-0.dev4"
description = "A Python implementation of a set of pntOS example plugins."
readme = "README.md"
license = "Apache-2.0"
license-files = [ "LICENSE" ]
authors = [ { name = "IS4S", email = "pntos@is4s.com" } ]
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "aspn23==0.1.0",
    "aspn23-lcm==0.1.0",
    "flask",
    "flask-socketio",
    "h5py>1",
    "lcm>=1.5.1,<2",
    "matplotlib",
    "navanalysis-lcm==0.1.5",
    "navanalysis-ros==0.1.2",
    "navtk==2.1.post8.dev0",
    "numpy; sys_platform!='win32'",
    "numpy>2.2,<2.5; sys_platform=='win32'",
    "pntos-api>=2.0.0,<3.0.0",
    "pntos-cobra-frontend>=0.1,<0.2",
    "pydantic>=2.0.0",
    "scipy>=1.15.2",
    "textual",
    "tqdm",
    "typing-extensions>=4.14.1",
]
scripts.catalog = "pntos.cobra.utils.plugins:cobra_catalog"

[tool.setuptools]
include-package-data = true
package-data.pntos-cobra = [ "advanced_plugins/ui/_static/dist/**/*" ]
