[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=68" ]

[project]
name = "pntos-extras"
version = "2.1.0-0.dev3"
description = "A Python implementation of a set of pntOS expansion plugins, building on those in Cobra."
readme = "README.md"
license = "Apache-2.0"
license-files = [ "LICENSE" ]
authors = [ { name = "IS4S", email = "pntos@is4s.com" } ]
requires-python = ">=3.10,<3.15"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "aspn23==0.1.0",
    "navtk==2.1.post8.dev0",
    "numpy",
    "pntos-api>=2.0.0,<3.0.0",
    "pntos-cobra>=2.1.0.post0.dev3,<=2.1.0.post0.dev4",
]
